const char stars_shader_source[] = "#version 330\n"
"\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"out vec4 finalColor;\n"
"\n"
"uniform float uTime;\n"
"uniform vec2 uResolution;\n"
"\n"
"// Custom controls from Raylib\n"
"uniform float uStarSize;       // Star size multiplier (default ~1.0)\n"
"uniform float uStarBrightness; // Brightness multiplier (default ~1.0)\n"
"uniform float uStarDensity;    // Grid density scale (default ~1.0)\n"
"uniform float uSeed;           // Seed to shift layout per map\n"
"\n"
"// Hash function incorporates uSeed for unique map layouts\n"
"float hash21(vec2 p) {\n"
"    p += vec2(uSeed, uSeed * 13.37);\n"
"    p = fract(p * vec2(123.34, 456.21));\n"
"    p += dot(p, p + 45.32);\n"
"    return fract(p.x * p.y);\n"
"}\n"
"\n"
"mat2 rotate2d(float angle) {\n"
"    float s = sin(angle);\n"
"    float c = cos(angle);\n"
"    return mat2(c, -s, s, c);\n"
"}\n"
"\n"
"float star(vec2 uv, float flare) {\n"
"    float d = length(uv);\n"
"    float m = 0.05 / d;\n"
"    \n"
"    float ray = max(0.0, 1.0 - abs(uv.x * uv.y * 1000.0));\n"
"    m += ray * flare;\n"
"    \n"
"    uv = rotate2d(3.14159 / 4.0) * uv;\n"
"    ray = max(0.0, 1.0 - abs(uv.x * uv.y * 1000.0));\n"
"    m += ray * flare * 0.4;\n"
"    \n"
"    m *= smoothstep(0.8, 0.2, d);\n"
"    return m;\n"
"}\n"
"\n"
"vec3 starLayer(vec2 uv, float time) {\n"
"    vec3 col = vec3(0.0);\n"
"    vec2 gv = fract(uv) - 0.5;\n"
"    vec2 id = floor(uv);\n"
"    \n"
"    for(int y = -1; y <= 1; y++) {\n"
"        for(int x = -1; x <= 1; x++) {\n"
"            vec2 offset = vec2(float(x), float(y));\n"
"            float n = hash21(id + offset);\n"
"            \n"
"            vec2 starPos = vec2(n - 0.5, fract(n * 34.0) - 0.5) * 0.7;\n"
"            vec2 p = gv - offset - starPos;\n"
"            \n"
"            float twinkle = sin(time * (2.0 + n * 3.0) + n * 6.2831) * 0.5 + 0.5;\n"
"            twinkle = pow(twinkle, 3.0);\n"
"            \n"
"            // Multiply star size by uStarSize\n"
"            float size = (fract(n * 123.45) * 0.5 + 0.5) * uStarSize;\n"
"            float flareIntensity = smoothstep(0.7, 1.0, size);\n"
"            \n"
"            // Multiply brightness intensity by uStarBrightness\n"
"            float intensity = star(p / size, flareIntensity) * (0.3 + 0.7 * twinkle) * uStarBrightness;\n"
"            vec3 starColor = sin(vec3(0.2, 0.5, 0.9) * n * 20.0) * 0.25 + 0.75;\n"
"            \n"
"            col += intensity * starColor * size;\n"
"        }\n"
"    }\n"
"    return col;\n"
"}\n"
"\n"
"void main() {\n"
"    vec2 uv = (gl_FragCoord.xy - 0.5 * uResolution.xy) / uResolution.y;\n"
"    vec3 stars = vec3(0.0);\n"
"    \n"
"    // Scale density across layers using uStarDensity\n"
"    stars += starLayer(uv * 4.0 * uStarDensity, uTime);\n"
"    stars += starLayer(uv * 8.0 * uStarDensity + vec2(10.5, 20.2), uTime * 1.2) * 0.6;\n"
"    stars += starLayer(uv * 16.0 * uStarDensity + vec2(50.1, 75.8), uTime * 0.8) * 0.3;\n"
"    \n"
"    vec3 background = mix(vec3(0.01, 0.02, 0.05), vec3(0.0, 0.0, 0.01), length(uv));\n"
"    finalColor = vec4(background + stars, 1.0) * fragColor;\n"
"}\n"
;